services:
  - type: web
    name: fixonest-frontend
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: PORT
        value: 3000
      - key: REACT_APP_BASE_URL
        value: https://fixonest-backend.onrender.com/api/
